<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <LangVersion>latest</LangVersion>
    <Authors>Hope House</Authors>
    <Company>Hope House</Company>
    <Copyright>Copyright © 2026 Hope House</Copyright>

    <!-- todo: enable
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    -->
  </PropertyGroup>
</Project>